name = "chronovue-site"
compatibility_date = "2026-06-01"
account_id = "7d17cac5edb074b44e111e08fde2b2d7"
workers_dev = false

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Add this section below (replace with your actual domain)
[[routes]]
pattern = "chronovue.co"
custom_domain = true

# Optional: If you also want it to work with www.
[[routes]]
pattern = "www.chronovue.co"
custom_domain = true
